name: epl
channels:
  - defaults
dependencies:
  - python=3.7
  - beautifulsoup4
  - flask
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - xmltodict
  - pip:
    - lxml
